Download Models From Model Registry (Prediction Server)
christopherkeim/crypto-real-time-inference pull request #29
Opened 2023-10-04 22:30 UTC by christopherkeim

## Added Functionality for Fetching Models From W&B Backend

1. `predict.py`: will pull models from W&B if a model does not exist on the machine (i.e. on a clean deployment)

2. `set_environment_variables_template.sh`: used in development for experiment tracking; for deployment simply replace `export WANDB_ENTITY="your-entity-name"` on `line 18` with your entity name (model registry must be public)

2023-10-05 01:16 UTC, kensonjohnson requested changes

2023-10-05 01:16 UTC, kensonjohnson commented on src/predict.py
This ends up adding extra logic to a sound API. Consider moving the downloading of models to the `setup.sh` step or in a deploy specific script.

2023-10-05 01:26 UTC, christopherkeim commented on src/predict.py
## TODO

`deploy` directory containing:

1. `setup_deploy.sh`: server setup for Python, Poetry, install dependencies with Poetry
2. `secrets.sh`: gather user input for wandb entity and source as environment variable
3. `download_models_from_wandb.py` script for downloading models to disk
4. `deploy.sh` calling scripts above and starting `server.py`

2023-10-07 03:38 UTC, kensonjohnson approved these changes

2023-10-07 03:54 UTC, merged